version: '3.8'

services:
    db:
        image: 'postgres'
        environment:
          - POSTGRES_DB=dbclear
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - '5432:5432'